Review communication
kottz/D7039E pull request #81
Opened 2020-12-16 17:06 UTC by edwced

2020-12-24 10:16 UTC, mnsnor commented
Don't know if it's just on my end, but all I can see is the bibliography. If that's the case then the push is fine

2020-12-24 11:04 UTC, edwced commented
Seems like the chapter got skipped. Trying to redo it. Or I'll remake it.

2020-12-27 12:17 UTC, Partins requested changes

2020-12-27 12:17 UTC, Partins commented on report/finished/bibliography.bib
> +  url = {https://www.ros.org},
Pretty sure this URL is wrong

2020-12-28 23:32 UTC, merged